# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cyberdog_app_pb2 as cyberdog__app__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cyberdog_app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GrpcAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendMsg = channel.unary_stream(
                '/grpcapi.GrpcApp/sendMsg',
                request_serializer=cyberdog__app__pb2.SendRequest.SerializeToString,
                response_deserializer=cyberdog__app__pb2.RecResponse.FromString,
                _registered_method=True)
        self.heartbeat = channel.unary_unary(
                '/grpcapi.GrpcApp/heartbeat',
                request_serializer=cyberdog__app__pb2.Ticks.SerializeToString,
                response_deserializer=cyberdog__app__pb2.Result.FromString,
                _registered_method=True)
        self.getFile = channel.unary_stream(
                '/grpcapi.GrpcApp/getFile',
                request_serializer=cyberdog__app__pb2.SendRequest.SerializeToString,
                response_deserializer=cyberdog__app__pb2.FileChunk.FromString,
                _registered_method=True)


class GrpcAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendMsg': grpc.unary_stream_rpc_method_handler(
                    servicer.sendMsg,
                    request_deserializer=cyberdog__app__pb2.SendRequest.FromString,
                    response_serializer=cyberdog__app__pb2.RecResponse.SerializeToString,
            ),
            'heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartbeat,
                    request_deserializer=cyberdog__app__pb2.Ticks.FromString,
                    response_serializer=cyberdog__app__pb2.Result.SerializeToString,
            ),
            'getFile': grpc.unary_stream_rpc_method_handler(
                    servicer.getFile,
                    request_deserializer=cyberdog__app__pb2.SendRequest.FromString,
                    response_serializer=cyberdog__app__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcapi.GrpcApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcapi.GrpcApp', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpcapi.GrpcApp/sendMsg',
            cyberdog__app__pb2.SendRequest.SerializeToString,
            cyberdog__app__pb2.RecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcapi.GrpcApp/heartbeat',
            cyberdog__app__pb2.Ticks.SerializeToString,
            cyberdog__app__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpcapi.GrpcApp/getFile',
            cyberdog__app__pb2.SendRequest.SerializeToString,
            cyberdog__app__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
